spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping-cart?currentSchema=shopping_cart
    username: shopping_cart_app
    password: localapppass

    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: AppPool

  application:
    name: shopping-cart-service

  flyway:
    enabled: true
    schemas: shopping_cart